# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI

on:
  [workflow_dispatch, push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, '[ciskip]')
    steps:
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '25'

      - name: Add permission
        run: chmod +x ./gradlew

      - name: Download local libraries
        run: ./gradlew downloadLocalLibs

      - name: Setup workspace
        run: ./gradlew setupDecompWorkspace

      - name: Build with Gradle
        run: ./gradlew build
        env:
          FTB_MAVEN_TOKEN: ${{ secrets.FTB_MAVEN_TOKEN }}
          SAPS_TOKEN: ${{ secrets.SAPS_TOKEN }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          path: build/libs